//------------------------------------------------------------------------------
// <auto-generated>look at the SelectIteratorGenerator.tt</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Slinq.Abstract;

namespace Slinq.Iterators
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1815:OverrideEqualsAndOperatorEqualsOnValueTypes", Justification = "Design")]
    public struct SelectEnumerator<TSource, TResult> : IStrongEnumerator<TResult>
    {
        private readonly TSource[] _source;
        private readonly int _actualLength;
        private readonly Func<TSource, TResult> _selector;
        private int _currentItemIndex;

        internal SelectEnumerator(TSource[] source, int actualLength, Func<TSource, TResult> selector)
        {
            _source = source;
            _actualLength = actualLength;
            _selector = selector;
            _currentItemIndex = -1;
        }

        public TResult Current
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return _selector(_source[_currentItemIndex]); }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool MoveNext()
        {
            return ++_currentItemIndex < _actualLength;
        }
    }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1815:OverrideEqualsAndOperatorEqualsOnValueTypes", Justification = "Design")]
    public struct SelectIterator<TSource, TResult> : IStrongEnumerable<TResult, SelectEnumerator<TSource, TResult>>, IFixedCount
    {
        private readonly TSource[] _source;
        private readonly int _actualLength;
        private readonly Func<TSource, TResult> _selector;

        internal SelectIterator(TSource[] source, int actualLength, Func<TSource, TResult> selector)
        {
            _source = source;
            _selector = selector;
            _actualLength = actualLength;
        }

        public int FixedCount
        {
            get { return _actualLength; }
        }

        public SelectEnumerator<TSource, TResult> GetEnumerator()
        {
            return new SelectEnumerator<TSource, TResult>(_source, _actualLength, _selector);
        }

        public SelectWhereIterator<TSource, TResult> Where(Predicate<TResult> predicate)
        {
            return new SelectWhereIterator<TSource, TResult>(_source, _actualLength, _selector, predicate);
        }

        public bool Any()
        {
            int index = 0;
            while (index < _actualLength)
            {
                return true;
            }

            return false;
        }

        public bool Contains(TResult item)
        {
            return Contains(item, EqualityComparer<TResult>.Default);
        }

        public bool Contains(TResult item, IEqualityComparer<TResult> equalityComparer)
        {
            int index = 0;
            while (index < _actualLength)
            {
                if (equalityComparer.Equals(_selector(_source[index]), item))
                {
                    return true;
                }
                ++index;
            }

            return false;
        }

        public int Count()
        {
            return FixedCount;
        }

        public TResult First()
        {
            int index = 0;
            while (index < _actualLength)
            {
                return _selector(_source[index]);
            }

            throw Error.NoElements();
        }

        public TResult FirstOrDefault()
        {
            int index = 0;
            while (index < _actualLength)
            {
                return _selector(_source[index]);
            }

            return default(TResult);
        }

        public TResult Last()
        {
            int index = _actualLength - 1;
            while (index >= 0)
            {
                return _selector(_source[index]);
            }

            throw Error.NoElements();
        }

        public TResult LastOrDefault()
        {
            int index = _actualLength - 1;
            while (index >= 0)
            {
                return _selector(_source[index]);
            }

            return default(TResult);
        }

        public TResult Single()
        {
            TResult single = default(TResult);
            bool hasFound = false;
            int index = 0;
            while (index < _actualLength)
            {
                if(hasFound)
                {
                    throw Error.MoreThanOneElement();
                }
                single = _selector(_source[index]);
                hasFound = true;
                ++index;
            }

            if(hasFound)
            {
                return single;
            }
            throw Error.NoElements();
        }

        public TResult SingleOrDefault()
        {
            TResult single = default(TResult);
            bool hasFound = false;
            int index = 0;
            while (index < _actualLength)
            {
                if(hasFound)
                {
                    throw Error.MoreThanOneElement();
                }
                single = _selector(_source[index]);
                hasFound = true;
                ++index;
            }

            return single;
        }
    }
}