//------------------------------------------------------------------------------
// <auto-generated>look at the SelectWhereIteratorGenerator.tt</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Slinq.Abstract;

namespace Slinq.Iterators
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1815:OverrideEqualsAndOperatorEqualsOnValueTypes", Justification = "Design")]
    public struct SelectWhereEnumerator<TSource, TResult> : IStrongEnumerator<TResult>
    {
        // we have so many fields here because "manual inling" is just performing better than pure calls to SelectIterator's MoveNext/Current
        private readonly TSource[] _source;
        private readonly int _actualLength;
        private readonly Func<TSource, TResult> _selector;
        private readonly Predicate<TResult> _predicate;
        private int _currentItemIndex;
        private TResult _current;

        internal SelectWhereEnumerator(TSource[] source, int actualLength, Func<TSource, TResult> selector, Predicate<TResult> predicate)
        {
            _source = source;
            _actualLength = actualLength;
            _selector = selector;
            _predicate = predicate;
            _currentItemIndex = -1;
            _current = default(TResult);
        }

        public TResult Current
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return _current; }
        }

        [MethodImplAttribute(MethodImplOptions.AggressiveInlining)]
        public bool MoveNext()
        {
            while (++_currentItemIndex < _actualLength)
            {
                var next = _selector(_source[_currentItemIndex]);
                if (_predicate(next))
                {
                    _current = next; // the selector might be quite expensive operation so we need to store it's result
                    return true;
                }
            }

            return false;
        }
    }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1815:OverrideEqualsAndOperatorEqualsOnValueTypes", Justification = "Design")]
    public struct SelectWhereIterator<TSource, TResult> : IStrongEnumerable<TResult, SelectWhereEnumerator<TSource, TResult>>
    {
        private readonly TSource[] _source;
        private readonly int _actualLength;
        private readonly Func<TSource, TResult> _selector;
        private readonly Predicate<TResult> _predicate;

        internal SelectWhereIterator(TSource[] source, int actualLength, Func<TSource, TResult> selector, Predicate<TResult> predicate)
        {
            _source = source;
            _actualLength = actualLength;
            _selector = selector;
            _predicate = predicate;
        }

        public SelectWhereEnumerator<TSource, TResult> GetEnumerator()
        {
            return new SelectWhereEnumerator<TSource, TResult>(_source, _actualLength, _selector, _predicate);
        }

        public bool Any()
        {
            int index = 0;
            while (index < _actualLength)
            {
                if(_predicate(_selector(_source[index])))
                {
                    return true;
                }
                ++index;
            }

            return false;
        }

        public bool Contains(TResult item)
        {
            return Contains(item, EqualityComparer<TResult>.Default);
        }

        public bool Contains(TResult item, IEqualityComparer<TResult> equalityComparer)
        {
            int index = 0;
            while (index < _actualLength)
            {
                if(_predicate(_selector(_source[index])))
                {
                    if (equalityComparer.Equals(_selector(_source[index]), item))
                    {
                        return true;
                    }
                }
                ++index;
            }

            return false;
        }

        public int Count()
        {
            int index = 0;
            int count = 0;
            while (index < _actualLength)
            {
                if(_predicate(_selector(_source[index])))
                {
                    ++count;
                }
                ++index;
            }

            return count;
        }

        public TResult First()
        {
            int index = 0;
            while (index < _actualLength)
            {
                if(_predicate(_selector(_source[index])))
                {
                    return _selector(_source[index]);
                }
                ++index;
            }

            throw Error.NoElements();
        }

        public TResult FirstOrDefault()
        {
            int index = 0;
            while (index < _actualLength)
            {
                if(_predicate(_selector(_source[index])))
                {
                    return _selector(_source[index]);
                }
                ++index;
            }

            return default(TResult);
        }

        public TResult Last()
        {
            int index = _actualLength - 1;
            while (index >= 0)
            {
                if(_predicate(_selector(_source[index])))
                {
                    return _selector(_source[index]);
                }
                --index;
            }

            throw Error.NoElements();
        }

        public TResult LastOrDefault()
        {
            int index = _actualLength - 1;
            while (index >= 0)
            {
                if(_predicate(_selector(_source[index])))
                {
                    return _selector(_source[index]);
                }
                --index;
            }

            return default(TResult);
        }

        public TResult Single()
        {
            TResult single = default(TResult);
            bool hasFound = false;
            int index = 0;
            while (index < _actualLength)
            {
                if(_predicate(_selector(_source[index])))
                {
                    if(hasFound)
                    {
                        throw Error.MoreThanOneElement();
                    }
                    single = _selector(_source[index]);
                    hasFound = true;
                }
                ++index;
            }

            if(hasFound)
            {
                return single;
            }
            throw Error.NoElements();
        }

        public TResult SingleOrDefault()
        {
            TResult single = default(TResult);
            bool hasFound = false;
            int index = 0;
            while (index < _actualLength)
            {
                if(_predicate(_selector(_source[index])))
                {
                    if(hasFound)
                    {
                        throw Error.MoreThanOneElement();
                    }
                    single = _selector(_source[index]);
                    hasFound = true;
                }
                ++index;
            }

            return single;
        }
    }
}